[package]
name = "nir"
version = "0.1.0"
edition = "2024"
license = "EUPL-1.2"
description = "An experimental nix implementation"

[dependencies]
camino = "1.1.9"
color-eyre = "0.6.4"
dashmap = "6.1.0"
ordered-float = "5.0.0"
rnix = "0.12.0"
rowan = "0.15"
salsa = "0.21.1"
